server:
  port: 8081

#mybatis:
#  mapper-locations: classpath:mapper/*Mapper.xml
spring:
  datasource:
    url: jdbc:mysql://47.95.237.152:3306/DarkSoul?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: Hadoop@123

mybatis:
  configuration:
    map-underscore-to-camel-case: true
mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: flag  # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
  #      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
  #      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#  mvc:
#    hiddenmethod:
#      filter:
#        enabled: true
#shiro-redis:
#  enabled: true
#  redis-manager:
#    host: 127.0.0.1:6379
#markerhub:
#  jwt:
#    secret: 123456789
#    expire: 604800
#    header: Authorization